services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nested:/var/www/nested
    depends_on:
      - php
    networks:
        - laravel-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_USER_ID: 1000
        HOST_GROUP_ID: 1000
    volumes:
      - ./nested:/var/www/nested
    working_dir: /var/www/nested
    networks:
        - laravel-network

  vite:
    build:
      context: .
      dockerfile: node.Dockerfile
      args:
        HOST_USER_ID: 1000
        HOST_GROUP_ID: 1000
    volumes:
      - ./nested:/var/www/nested
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    working_dir: /var/www/nested
    command: sh -c "npm install && npm run dev -- --host"
    networks:
        - laravel-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
        - laravel-network

  pgsql:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=laravel_db
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U laravel" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - laravel-network

volumes:
  redis_data:
  postgres_data:

networks:
  default:
    name: laravel-network