version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nested:/var/www/nested
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_USER_ID: 1000
        HOST_GROUP_ID: 1000
    volumes:
      - ./nested:/var/www/nested
    working_dir: /var/www/nested

  vite:
    build:
      context: .
      dockerfile: node.Dockerfile
      args:
        HOST_USER_ID: 1000
        HOST_GROUP_ID: 1000
    volumes:
      - ./nested:/var/www/nested
    ports:
      - "5173:5173"
    environment:
      - NPM_CONFIG_CACHE=/tmp/.npm
    working_dir: /var/www/nested
    command: sh -c "npm install && npm run dev -- --host"

networks:
  default:
    name: laravel-network