# services:
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#       - ./top:/var/www/top
#       - ./nested:/var/www/nested
#     depends_on:
#       - php

#   php:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       args:
#         HOST_USER_ID: 1000  # Altere se necessário para corresponder ao seu UID
#         HOST_GROUP_ID: 1000 # Altere se necessário para corresponder ao seu GID
#     volumes:
#       - ./top:/var/www/top
#       - ./nested:/var/www/nested
#     working_dir: /var/www

# networks:
#   default:
#     driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nested:/var/www/nested:ro
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_USER_ID: 1000
        HOST_GROUP_ID: 1000
    volumes:
      - ./nested:/var/www/nested
    working_dir: /var/www/nested

networks:
  default:
    driver: bridge
